name: transportation_mobile_app
description: Enhancing vehicle transportation.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  flutter_modular: ^3.2.2+1
  dio: ^4.0.0
  enum_to_string: ^2.0.1
  flutter_dotenv: ^3.1.0
  url_launcher: ^6.0.3
  google_fonts: ^2.0.0
  maps_launcher: ^2.0.0
  intl: ^0.17.0
  percent_indicator: ^2.1.7+2
  dotted_border: ^2.0.0+1
  camera: ^0.9.4+5
  signature: ^4.1.1
  toggle_switch: ^1.2.0
  shared_preferences: ^2.0.5
  path_provider: ^2.0.6
  location: ^4.3.0
  syncfusion_flutter_pdfviewer: ^19.3.0
  flutter_picker: ^2.0.2
  permission_handler: ^8.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  syncfusion_flutter_pdf: ^19.3.53-beta
  native_pdf_view: ^5.0.0
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/launcher_icons/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/1_Splash_1_Image1.png
    - assets/2_Splash_2_Image1.png
    - assets/3_Splash_3_Image1.png
    - assets/logo.png
    - assets/map-preview.png
    - assets/profilephoto.png
    - assets/twitter.svg
    - assets/Wallet.svg
    - assets/Horizontal_view.svg
    - assets/Pulse_machine.svg
    - assets/Credit_card.svg
    - assets/tire.png
    - assets/front_seats.png
    - assets/odometer.png
    - assets/trunk.png
    - assets/dashboard.png
    - assets/steering.png
    - assets/rear_seats.png
    - assets/diagonal_back.png
    - assets/diagonal_front.png
    - assets/left.png
    - assets/right.png
    - assets/back.png
    - assets/front.png
    - assets/top.png
    - assets/vin_reader.png
    - assets/attachment-1.png
    - assets/attachment-2.png
    - assets/attachment-3.png
    - assets/attachment-4.png
    - assets/attachment-5.png
    - assets/attachment-6.png
    - assets/inspection_config.json
    - assets/ssd_mobilenet.tflite
    - assets/ssd_mobilenet.txt
    - assets/record.gif
    - assets/info.svg
    - assets/mechanic.svg
    - assets/exterior.svg
    - assets/interior.svg
    - assets/tier.svg
    - assets/camera.svg
    - assets/document.svg
    - assets/record.gif
    - assets/feature.svg
    - assets/panorama.svg
    - assets/pause.svg
    - assets/search.svg
    - assets/car_pic.png
    - assets/car_pic_big.png
    - assets/phone_msg.svg
    - assets/location.svg
    - assets/settings.svg
    - assets/completed_session.svg
    - assets/pending_approved_session.svg
    - assets/uploading_session.svg
    - assets/upcoming_session.svg
    - assets/ongoing_session.svg
    - assets/car_background.jpg
    - assets/right_circle.svg
    - assets/car_info.svg
    - assets/car_info.png
    - assets/calendar.svg
    - assets/clock.svg
    - assets/car_front.svg
    - assets/check_circle.svg
    - assets/qr.svg
    - assets/mic.svg
    - assets/phone_customer.png
    - assets/phone_user.png
    - assets/first_tab.svg
    - assets/normal_tab.svg
    - assets/normal_tab_red.svg
    - assets/unselect.svg
    - assets/recording_gif.gif
    - assets/missing_error.png
    - assets/vin.png
    - assets/lottie/recoding.json
    - assets/bill.pdf
    - assets/reporting_issues/iss_back.png
    - assets/reporting_issues/iss_front.png
    - assets/reporting_issues/iss_left.png
    - assets/reporting_issues/iss_right.png
    - assets/reporting_issues/iss_top.png
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
